# Generated by Django 5.0.3 on 2024-04-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('1', 'Validé'), ('2', 'Annulé')], default='1', max_length=30, verbose_name='Statut'),
        ),
    ]
