# Generated by Django 5.0.3 on 2024-06-25 07:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_add_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, verbose_name='Montant de la réduction'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
