# Generated by Django 5.0.3 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_add_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Vente'), ('can_change', 'Modifier - Vente'), ('can_delete', 'Supprimer - Vente'), ('can_view', 'Voir - Vente')]},
        ),
    ]
