# Generated by Django 5.0.3 on 2024-06-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'default_permissions': [], 'permissions': [('can_add_sale', 'Ajouter - Vente'), ('can_change_sale', 'Modifier - Vente'), ('can_delete_sale', 'Supprimer - Vente'), ('can_view_sale', 'Voir - Vente')], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
    ]
