# Generated by Django 5.0.3 on 2024-06-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_sale_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='products',
        ),
    ]
