# Generated by Django 5.0.3 on 2024-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sale_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
