# Generated by Django 5.0.3 on 2024-04-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='EditableSettings',
        ),
    ]
