# Generated by Django 5.0.3 on 2024-05-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_settings_editablesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editablesettings',
            name='pin_code',
        ),
    ]
