# Generated by Django 5.0.3 on 2024-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_editablesettings_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablesettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo entreprise'),
        ),
    ]
