# Generated by Django 5.0.3 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_editablesettings_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editablesettings',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Paramètre'), ('can_change', 'Modifier - Paramètre'), ('can_delete', 'Supprimer - Paramètre'), ('can_view', 'Voir - Paramètre')]},
        ),
    ]
