# Generated by Django 5.0.3 on 2024-06-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_editablesettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editablesettings',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Paramètre'), ('can_change', 'Modifier - Paramètre'), ('can_delete', 'Supprimer - Paramètre'), ('can_view', 'Voir - Paramètre')], 'verbose_name': 'Paramètre', 'verbose_name_plural': 'Paramètres'},
        ),
    ]
