# Generated by Django 5.0.3 on 2024-06-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_editablesettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editablesettings',
            options={'default_permissions': [], 'permissions': [('can_add_setting', 'Ajouter - Paramètre'), ('can_change_setting', 'Modifier - Paramètre'), ('can_delete_setting', 'Supprimer - Paramètre'), ('can_view_setting', 'Voir - Paramètre')], 'verbose_name': 'Paramètre', 'verbose_name_plural': 'Paramètres'},
        ),
    ]
