# Generated by Django 5.0.3 on 2024-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accent_color_code',
            field=models.CharField(choices=[('#4a75a0', '#4a75a0'), ('#a04a8f', '#a04a8f'), ('#a06a4a', '#a06a4a')], default='#4a75a0', max_length=15, null=True, verbose_name='Thème'),
        ),
    ]
