# Generated by Django 5.0.3 on 2024-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_accent_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='accent_color_code',
            field=models.CharField(choices=[('Bleu', '#4a75a0'), ('Violet', '#a04a8f'), ('Orange', '#a06a4a')], default='Bleu', max_length=15, null=True, verbose_name='Thème'),
        ),
    ]
