# Generated by Django 5.0.3 on 2024-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_accent_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='accent_color_code',
            field=models.CharField(choices=[('#4a75a0', 'Bleu'), ('#a04a8f', 'Violet'), ('#a06a4a', 'Orange')], default='#4a75a0', max_length=15, null=True, verbose_name='Thème'),
        ),
    ]
