# Generated by Django 5.0.3 on 2024-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_accent_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('telecom', 'Télécommunication'), ('breeding', 'Elevage'), ('other', 'Autre')], default='other', max_length=150, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='store',
            name='accent_color_code',
            field=models.CharField(choices=[('#4a75a0', 'Bleu'), ('#a04a8f', 'Violet'), ('#a06a4a', 'Orange sombre'), ('#BB4430', 'Rouge sombre'), ('#13293D', 'Bleu sombre'), ('#AA4465', 'Rose sombre'), ('#474056', 'Violet sombre')], default='#4a75a0', max_length=15, null=True, verbose_name='Thème'),
        ),
    ]
