# Generated by Django 5.0.3 on 2024-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_category_alter_store_accent_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('telecom', 'Télécommunication'), ('breeding', 'Elevage'), ('electronic', 'Electroménager'), ('other', 'Autre')], default='other', max_length=150, null=True, verbose_name='Catégorie'),
        ),
    ]
