# Generated by Django 5.0.3 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_add_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Magasin'), ('can_change', 'Modifier - Magasin'), ('can_delete', 'Supprimer - Magasin'), ('can_view', 'Voir - Magasin')]},
        ),
    ]
