# Generated by Django 5.0.3 on 2024-06-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_store_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Magasin'), ('can_change', 'Modifier - Magasin'), ('can_delete', 'Supprimer - Magasin'), ('can_view', 'Voir - Magasin')], 'verbose_name': 'Magasin', 'verbose_name_plural': 'Magasins'},
        ),
    ]
