# Generated by Django 5.0.3 on 2024-06-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_alter_store_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'default_permissions': [], 'permissions': [('can_add_store', 'Ajouter - Magasin'), ('can_change_store', 'Modifier - Magasin'), ('can_delete_store', 'Supprimer - Magasin'), ('can_view_store', 'Voir - Magasin'), ('can_access_all_store', 'Accès à tous les magasins')], 'verbose_name': 'Magasin', 'verbose_name_plural': 'Magasins'},
        ),
    ]
