# Generated by Django 5.0.3 on 2024-05-15 18:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_alter_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_by', models.CharField(max_length=150, verbose_name='Accordé par')),
                ('granted_date', models.DateField(verbose_name='Accordé le')),
                ('initial_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Montant initial')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Commande liée')),
            ],
        ),
        migrations.CreateModel(
            name='DebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Montant')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debts.debt', verbose_name='Dette remboursé')),
            ],
        ),
    ]
