# Generated by Django 5.0.3 on 2024-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_alter_debtrepayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtrepayment',
            name='repaid_by',
            field=models.CharField(choices=[('money', 'Espèce'), ('product', 'Marchandise'), ('service', 'Service')], default='money', max_length=30, verbose_name='Payé en'),
        ),
    ]
