# Generated by Django 5.0.3 on 2024-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_debtrepayment_repaid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='add_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='debtrepayment',
            name='add_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
