# Generated by Django 5.0.3 on 2024-05-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_debt_add_at_debtrepayment_add_at'),
        ('orders', '0017_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Commande liée'),
        ),
    ]
