# Generated by Django 5.0.3 on 2024-05-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_alter_debt_order'),
        ('stores', '0008_store_add_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='order',
        ),
        migrations.AddField(
            model_name='debt',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Magasin'),
        ),
    ]
