# Generated by Django 5.0.3 on 2024-05-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_remove_debt_order_debt_store'),
        ('stores', '0008_store_add_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Magasin'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store', verbose_name='Magasin'),
        ),
    ]
