# Generated by Django 5.0.3 on 2024-05-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0007_debt_store_name_alter_debt_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_type',
            field=models.CharField(choices=[('incoming', 'Entrant'), ('outgoing', 'Sortant')], default='outgoing', max_length=15, verbose_name="Type d'impayé"),
        ),
    ]
