# Generated by Django 5.0.3 on 2024-05-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0008_debt_debt_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='granted_by',
            new_name='person_concerned',
        ),
    ]
