# Generated by Django 5.0.3 on 2024-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0009_auto_20240530_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='person_concerned',
            field=models.CharField(max_length=150, verbose_name='Personne concernée'),
        ),
    ]
