# Generated by Django 5.0.3 on 2024-06-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0010_alter_debt_person_concerned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'permissions': [('can_add', 'Ajouter - Impayé'), ('can_change', 'Modifier - Impayé'), ('can_delete', 'Supprimer - Impayé'), ('can_view', 'Voir - Impayé')]},
        ),
    ]
