# Generated by Django 5.0.3 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0012_alter_debt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtrepayment',
            options={'default_permissions': [], 'permissions': [('can_add', "Ajouter - Reboursement d'Impayé"), ('can_change', "Modifier - Reboursement d'Impayé"), ('can_delete', "Supprimer - Reboursement d'Impayé"), ('can_view', "Voir - Reboursement d'Impayé")]},
        ),
    ]
