# Generated by Django 5.0.3 on 2024-06-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0014_alter_debt_options_alter_debtrepayment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'default_permissions': [], 'permissions': [('can_add_debt', 'Ajouter - Impayé'), ('can_change_debt', 'Modifier - Impayé'), ('can_delete_debt', 'Supprimer - Impayé'), ('can_view_debt', 'Voir - Impayé')], 'verbose_name': 'Impayé', 'verbose_name_plural': 'Impayés'},
        ),
        migrations.AlterModelOptions(
            name='debtrepayment',
            options={'default_permissions': [], 'permissions': [('can_add_repayment', "Ajouter - Reboursement d'Impayé"), ('can_change_repayment', "Modifier - Reboursement d'Impayé"), ('can_delete_repayment', "Supprimer - Reboursement d'Impayé"), ('can_view_repayment', "Voir - Reboursement d'Impayé")], 'verbose_name': "Remboursement d'Impayé", 'verbose_name_plural': "Remboursements d'Impayé"},
        ),
    ]
