# Generated by Django 5.0.3 on 2024-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price_sale',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_unit_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
