# Generated by Django 5.0.3 on 2024-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit_price_sale_product_wholesale_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Paquetage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price_sale',
            field=models.FloatField(default=0.0, null=True, verbose_name='Prix unitaire vente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_unit_price',
            field=models.FloatField(default=0.0, null=True, verbose_name='Prix unitaire gros'),
        ),
    ]
