# Generated by Django 5.0.3 on 2024-04-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paquetage'),
        ),
    ]
