# Generated by Django 5.0.3 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_created_at_product_add_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Produit'), ('can_change', 'Modifier - Produit'), ('can_delete', 'Supprimer - Produit'), ('can_view', 'Voir - Produit')]},
        ),
    ]
