# Generated by Django 5.0.3 on 2024-06-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Produit'), ('can_change', 'Modifier - Produit'), ('can_delete', 'Supprimer - Produit'), ('can_view', 'Voir - Produit')], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
