# Generated by Django 5.0.3 on 2024-05-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usermodel_first_name_alter_usermodel_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
