# Generated by Django 5.0.3 on 2024-05-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserPreference',
        ),
    ]
