# Generated by Django 5.0.3 on 2024-05-29 12:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_userprofile_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[accounts.models.pin_code_verification], verbose_name='Code pin'),
        ),
    ]
