# Generated by Django 5.0.3 on 2024-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_usermodel_is_active_alter_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name="Membre d'équipe"),
        ),
    ]
