# Generated by Django 5.0.3 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_usermodel_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Utilisateur'), ('can_change', 'Modifier - Utilisateur'), ('can_delete', 'Supprimer - Utilisateur'), ('can_view', 'Voir - Utilisateur')]},
        ),
    ]
