# Generated by Django 5.0.3 on 2024-06-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Utilisateur'), ('can_change', 'Modifier - Utilisateur'), ('can_delete', 'Supprimer - Utilisateur'), ('can_view', 'Voir - Utilisateur')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
