# Generated by Django 5.0.3 on 2024-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customgroup_alter_usermodel_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, to='accounts.customgroup', verbose_name='Groupes'),
        ),
    ]
