# Generated by Django 5.0.3 on 2024-06-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_usermodel_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
    ]
