# Generated by Django 5.0.3 on 2024-06-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_usermodel_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'default_permissions': [], 'permissions': [('can_add_user', 'Ajouter - Utilisateur'), ('can_change_user', 'Modifier - Utilisateur'), ('can_delete_user', 'Supprimer - Utilisateur'), ('can_view_user', 'Voir - Utilisateur')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
