# Generated by Django 5.0.3 on 2024-06-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_delete_customgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'default_permissions': [], 'permissions': [('can_add_user', 'Ajouter - Utilisateur'), ('can_change_user', 'Modifier - Utilisateur'), ('can_delete_user', 'Supprimer - Utilisateur'), ('can_view_user', 'Voir - Utilisateur'), ('can_access_global_stats', 'Accès aux statitiques et inventaires globaux')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
