# Generated by Django 5.0.3 on 2024-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_shipped_order_shipping_costs'),
        ('products', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrived_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_shipped',
            field=models.BooleanField(blank=True, default=False, verbose_name='Livré'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='products.product', verbose_name='Produits inclus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_name',
            field=models.CharField(max_length=150, verbose_name='Nom du fournisseur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_phone',
            field=models.CharField(max_length=30, verbose_name='Téléphone du fournisseur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_costs',
            field=models.FloatField(default=0.0, null=True, verbose_name='Frais de livraison'),
        ),
    ]
