# Generated by Django 5.0.3 on 2024-04-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du fournisseur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone du fournisseur'),
        ),
    ]
