# Generated by Django 5.0.3 on 2024-04-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_provider_name_alter_order_provider_phone'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Magasin'),
        ),
    ]
