# Generated by Django 5.0.3 on 2024-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_shipping_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'En cours'), ('1', 'Livré'), ('2', 'Annulé')], default='0', max_length=30, verbose_name='Livraison'),
        ),
    ]
