# Generated by Django 5.0.3 on 2024-05-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
