# Generated by Django 5.0.3 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': [], 'permissions': [('can_add', 'Ajouter - Commande'), ('can_change', 'Modifier - Commande'), ('can_delete', 'Supprimer - Commande'), ('can_view', 'Voir - Commande')]},
        ),
    ]
