# Generated by Django 5.0.3 on 2024-06-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': [], 'permissions': [('can_add_order', 'Ajouter - Commande'), ('can_change_order', 'Modifier - Commande'), ('can_delete_order', 'Supprimer - Commande'), ('can_view_order', 'Voir - Commande')], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
    ]
