# Generated by Django 5.0.3 on 2024-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='added_to_stock',
            field=models.BooleanField(default=False),
        ),
    ]
