# Generated by Django 5.0.3 on 2024-06-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_added_to_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_shipped',
        ),
    ]
